### PR TITLE
tests: Fix TestGetRemoteEntrypoint network access 👼

### LINKED ISSUE #268: TestGetRemoteEntrypoint makes real HTTP requests
## Expected Behavior

I can run Go tests without a connection to the internet.

## Actual Behavior

`TestGetRemoteEntrypoint` panics because the registry can't be found, and the error doesn't result in a `t.Fatal`

## Steps to Reproduce the Problem

  1. Disconnect wifi
  2. `go test ./...`

## Additional Info

This test would also fail if the Kaniko image changed its entrypoint.

Unit tests shouldn't depend on external state. Instead, HTTP requests should be mocked out in the client, or even better, the image should be served from a local HTTP server that's spun up in the test, using `net/http/httptest`.

### PR DESCRIPTION
**Pull request by vdemeester**
A unit test shouldn't require network connectivity. This test was and
would panic if not connected to the internet.

This tests now uses `net/http/httptest` to "act as" a registry.

Closes #268 

/cc @ImJasonH 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

File: pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go [hunk 1]
```diff
@@ -72,13 +80,100 @@ func TestAddEntrypoint(t *testing.T) {
...
+	}))
+	defer server.Close()
+	image := path.Join(strings.TrimPrefix(server.URL, "http://"), "kaniko:latest")
+	ep, err := entrypoint.GetRemoteEntrypoint(entrypoint.NewCache(), image)
 	if err != nil {
 		t.Errorf("couldn't get entrypoint remote: %v", err)
 	}
 	if len(ep) != 1 {
-		t.Errorf("remote entrypoint should only have one item")
+		t.Fatalf("remote entrypoint should only have one item")
```
Comment (vdemeester) [inline pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go]: Changed this to fatal as with `Errorf` it will panic on the next `if` :wink:

File: pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go [hunk 2]
```diff
@@ -72,13 +80,100 @@ func TestAddEntrypoint(t *testing.T) {
...
+	}
+	return c
+}
+
+func getImage(t *testing.T, cfg *v1.ConfigFile) v1.Image {
+	rnd, err := partial.UncompressedToImage(&image{
+		config: cfg,
+	})
+	if err != nil {
+		t.Fatalf("random.Image() = %v", err)
```
Comment (ImJasonH) [inline pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go]: I don't think this error makes sense here.

File: pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go [hunk 3]
```diff
@@ -72,13 +80,100 @@ func TestAddEntrypoint(t *testing.T) {
...
+}
+
 func TestGetRemoteEntrypoint(t *testing.T) {
-	ep, err := entrypoint.GetRemoteEntrypoint(entrypoint.NewCache(), kanikoImage)
+	img := getImage(t, &v1.ConfigFile{
+		ContainerConfig: v1.Config{
+			Entrypoint: []string{kanikoEntrypoint},
+		},
+	})
+	expectedRepo := "kaniko"
```
Comment (ImJasonH) [inline pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go]: I think we should avoid using meaningful terms like "kaniko" here now that it has nothing to do with the kaniko image.

File: pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go (hunk 1 above)
Comment (ImJasonH) [reply pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go]: Very nice. For brevity, you could check both at once:

```
if !reflect.DeepEqual(ep, []string{"expected-entrypoint"}) {
  t.Error(...)
}
```

Now that we're not tied to the Kaniko image you could also check that multiple-valued entrypoints work as expected.

Comment (vdemeester) [reply pkg/reconciler/v1alpha1/taskrun/entrypoint/entrypoint_test.go]: @ImJasonH good point :wink:

**Comment by bobcatfish** [comment]
awesome, thanks for doing this @vdemeester

**Comment by aaron-prindle** [comment]
thanks for this!
