### PR TITLE
Run the examples yaml as an integration test

### LINKED ISSUE #108: Create end to end tests for our examples
## Expected Behavior
We should have a set of example `Pipelines` and `Tasks` (currently in `examples`) which folks can look use as reference to create their own, or even use as is.

These should be regularly tested so we can be sure they are working. We expect the actual test coverage of the Pipeline itself to happen in our integration tests (in `test`), so this task is simply about making sure the examples work, not about adding coverage (tho we'll probably get that for free anyway).

## Actual Behavior
Once #20 is resolved, we will be deploying the yamls in `examples` (via `examples/smoke-test.sh`) as part of integration testing, so we will know they comply with the schema, but not that they actually work (i.e. successfully do what they are trying to do).

## Steps to Reproduce the Problem
If the examples were to try to run a Build step that contains an image that doesn't exist for example, the integration test script would still pass, but the example wouldn't actually work.

## Additional Info
[The Build CRD tests do something very similar](https://github.com/knative/build/tree/master/test/e2e#end-to-end-tests) to what we need here, though since we are using our integration tests for coverage, we probably don't need the invalid tests (just successful tests).

### PR DESCRIPTION
**Pull request by pivotal-nader-ziada**
Fixes #108 

## Proposed Changes
 - remove smoke test script and use e2e script running yaml test
 - check status of pipelineRun to make sure the yaml worked

### CODE REVIEW

File: test/e2e-tests.sh [hunk 1]
```diff
@@ -66,6 +119,14 @@ go_test_e2e -timeout=20m ./test || fail_test
 # Run these _after_ the integration tests b/c they don't quite work all the way
 # and they cause a lot of noise in the logs, making it harder to debug integration
 # test failures.
-./examples/smoke-test.sh || fail_test
```
Comment (vdemeester) [inline test/e2e-tests.sh]: shouldn't `smoke-test.sh` script removed then ? :angel:

Comment (pivotal-nader-ziada) [reply test/e2e-tests.sh]: yes, I actually removed it but didn't push that, will remove it now for real 😄

File: test/e2e-tests.sh [hunk 2]
```diff
@@ -66,6 +119,14 @@ go_test_e2e -timeout=20m ./test || fail_test
...
-
+header "Running YAML e2e tests"
+if ! run_yaml_tests; then
+  failed=1
+  echo "ERROR: one or more YAML tests failed"
+  # If formatting fails for any reason, use yaml as a fall back.
+  kubectl get pipelinerun.pipeline.knative.dev -o=custom-columns-file=./test/columns.txt || \
```
Comment (shashwathi) [inline test/e2e-tests.sh]: This checks for status of pipelinerun only and not taskrun. I think testing for taskrun as well would be good. 
I would prefer the following order
- check for taskrun status to be successful 
- check for pipelinerun status to be successful

We can add examples of one off task and taskruns too in example in future.

File: test/e2e-tests.sh [hunk 3]
```diff
@@ -40,6 +40,59 @@ function dump_extra_cluster_state() {
   kubectl -n knative-build-pipeline logs $(get_app_pod build-pipeline-webhook knative-build-pipeline)
 }
 
+function run_yaml_tests() {
+  echo ">> Starting tests"
+
+  sed -i.bak 's/christiewilson-catfactory/${KO_DOCKER_REPO}/' examples/resources.yaml
```
Comment (bobcatfish) [inline test/e2e-tests.sh]: 😅 

(btw you know it turns out that `yq` is pretty good at this kinda thing! but i guess we probably dont want to bother vendoring it just for this)

File: test/e2e-tests.sh [hunk 4]
```diff
@@ -40,6 +40,59 @@ function dump_extra_cluster_state() {
...
+      if [[ ! "${result,,}" == *"=${want}" ]]; then
+	echo "ERROR: test ${result} but should be ${want}"
+	failed=1
+      fi
+    done
+  done
+  (( failed )) && return 1
+  echo ">> All YAML tests passed"
+  return 0
+}
```
Comment (bobcatfish) [inline test/e2e-tests.sh]: could the commit message maybe include the fact that this came from https://github.com/knative/build/blob/f7397a3ec59278416aac4890a5a08783c86e5353/test/e2e-common.sh , just in case we need to track it down one day?

(p.s. would be awesome to re-implement this in Go or even Python - but np if you dont want to do that now)

Comment (pivotal-nader-ziada) [reply test/e2e-tests.sh]: yeah, I wanted to get it done in bash first as the fastest way, then refactor later. Probably Go is better so we don't introduce another language

**Comment by pivotal-nader-ziada** [comment]
/test pull-knative-build-pipeline-integration-tests

one last time
