### PR TITLE
Git pull on fetch fail plus tests

### LINKED ISSUE #543: Can't specify any arbitrary commit id in git resource
## Expected Behavior
Use the revision param in the git resource to specify any arbitrary commit should pull the git repo at this commit

## Actual Behavior
specifying a commit hash in the `revision` param results in an error 
```
error: Server does not allow request for unadvertised object 0b4133b...26bd2e2d
``` 

## Steps to Reproduce the Problem

1. Use a git resource with an commit hash in the revision param

## Additional Info

From slack by @duane
```
Further to @Adam Roberts’s question above, one of the things we noticed during prototyping with build-pipeline was that you couldn't specify any arbitrary commit id ..... as the cmd/git-init/main.go does a git fetch (and you end up with errors about getting unadvertised commits)..... searching around on the web, there seemed to be various references to git properties you might be able to set on the server side to get unadvertised commits but I couldn't seem to get things working.

Interested to know if there is some magic I am missing - or if a code change is needed here.  To get around it, I forked the code and modified the code to do ....

```run(logger, "git", "pull", "--recurse-submodules=yes", "origin")
runOrFail(logger, "git", "checkout", *revision)```


seems to pass the go tests and happy to create PR to contribute, but thought I should check if I'm missing something in terms of using ANY commit id.  Additionally, no doubt we could argue about performance regarding fetch and pull .... the error you will get doing a pull with no branch listed (although the pull succeeds) .... and whether there should be an additional property to revision and path where you can specify a commit id ... and then if a commitid is specified do the git pull otherwise do the git fetch???
```

### PR DESCRIPTION
**Pull request by dibbles**
Fixes #543 a bug where the code source fails to be extracted from git, this happens when an old commit id is used that is not the HEAD of any branch.

## Changes

If the git fetch happens to error, a git pull is attempted.  Whilst the run method has been modified to return an error, the error is only checked in the case of the git fetch, this was done to minimize the code change at this time.

Some tests have been added that use differing revisions (short commitID, long commitID, branch name etc...) and ensure pipelines run to completion.  An additional test was added to ensure that if a revision is specified that is not valid, we receive the expected errors from git fetch and git pull.

## Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#commit-messages)

## Release Notes

No user facing changes - bug fix - no doc changes needed

Additional Note - running tests locally required changing some timeouts.  These changes have not been added with this initial commit as unknown whether this was specific to the environment in which I was running.

### CODE REVIEW

File: test/git_checkout_test.go [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+	gitTestPipelineRunName = "git-check-pipeline-run"
+)
+
+// TestGitPipelineRun is an integration test that will verify the source code is either fetched or pulled
+// successfully under different revision inputs (branch, commitid, tag, ref)
+func TestGitPipelineRun(t *testing.T) {
+	logger := logging.GetContextLogger(t.Name())
+	t.Parallel()
+
+	revisions := []string{"c15aced0e5aaee6456fbe6f7a7e95e0b5b3b2b2f", "c15aced", "release-0.1", "v0.1.0", "refs/pull/347/head"}
```
Comment (pivotal-nader-ziada) [inline test/git_checkout_test.go]: can we add a case for `master` to make sure everything is fine when its using the fetch

File: test/git_checkout_test.go [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+
+		if err := WaitForPipelineRunState(c, gitTestPipelineRunName, timeout, PipelineRunSucceed(gitTestPipelineRunName), "PipelineRunCompleted"); err != nil {
+			t.Errorf("Error waiting for PipelineRun %s to finish: %s", gitTestPipelineRunName, err)
+			taskruns, err := c.TaskRunClient.List(metav1.ListOptions{})
+			if err != nil {
+				t.Errorf("Error getting TaskRun list for PipelineRun %s %s", gitTestPipelineRunName, err)
+			}
+			for _, tr := range taskruns.Items {
+				if tr.Status.PodName != "" {
+					CollectBuildLogs(c, tr.Status.PodName, namespace, logger)
```
Comment (pivotal-nader-ziada) [inline test/git_checkout_test.go]: I don't think the `collectBuildLogs` is adding any value here, we just want to check the `PipelineRunStatus` or the `taskRunStatus` is successful

File: test/git_checkout_test.go (hunk 1 above)
Comment (dibbles) [reply test/git_checkout_test.go]: Done.

File: test/git_checkout_test.go (hunk 2 above)
Comment (dibbles) [reply test/git_checkout_test.go]: Removed.

**Comment by dibbles** [comment]
Additional commit added after review comments from @pivotal-nader-ziada

**Comment by pivotal-nader-ziada** [comment]
looks good to me, thanks @dibbles 

/lgtm
/approve

**Comment by pivotal-nader-ziada** [comment]
@ImJasonH @shashwathi might be a good idea to port a similar change to `build`

**Comment by bobcatfish** [comment]
Excellent @dibbles !! Thanks so much for taking care of this :D

(I'm gonna update the release notes to include the bug fix info)
