### PR TITLE
Taskrun CRD validation

### LINKED ISSUE #33: Add validation to controller for TaskRun CRD
## Expected Behavior

When someone creates a [TaskRun](https://github.com/knative/build-pipeline#taskrun) in a k8s cluster (e.g. with [kubectl apply](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running), the controller should make sure every field is valid.

This should include verifying as many fields as possible, e.g. verifying connectivity with any endpoints, if there are any references, verifying that those actually exist in the system, etc.

TaskRun is defined here: https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1beta1/taskrun_types.go

Any additional fields included should cause a failure (e.g. if a typo is made when defining a known field).

## Actual Behavior

Some basic validation is applied, e.g. that required fields are present and that fields are in the correct format (e.g. string vs. int), but that's it.

## Steps to Reproduce the Problem

1. [Deploy the Pipeline CRDs to your k8s cluster](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running)
2. Create an instance that has invalid fields, e.g. a malformed URL or a typo in one of the fields.
3. Apply the instance with `kubectl apply -f` and notice that the controller does not complain

## Additional Info
_Blocked by #19_

### PR DESCRIPTION
**Pull request by shashwathi**
Fixes #33 
- Added taskrun CRD validation
- Added tests for metadata validation

### CODE REVIEW

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 1]
```diff
@@ -0,0 +1,313 @@
...
+				TaskRef: TaskRef{
+					Name: "taskrefname",
+				},
+				Outputs: Outputs{
+					Resources: []TaskResource{{
+						Type: "invalidtype",
+					}},
+				},
+			},
+			// TODO(shashwathi): wrong error msg
```
Comment (pivotal-nader-ziada) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: can we fix the error msg?

Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: Damn I was suppose to fix it before sending PR :D

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+		return apis.ErrMissingField("spec.taskref.name")
+	}
+
+	// Check for Trigger
+	if err := validateTaskTriggerType(ts.Trigger.TriggerRef, "spec.trigger.triggerref.type"); err != nil {
+		return err
+	}
+
+	// check for input resources
+	if err := checkForipelineResourceDuplicates(ts.Inputs.Resources, "spec.Inputs.Resources.Name"); err != nil {
```
Comment (dlorenc) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: Looks like there's a typo here, the P in Pipeline is missing

File: pkg/apis/pipeline/v1alpha1/metadata_validation_test.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+	invalidMetas := []*metav1.ObjectMeta{
+		&metav1.ObjectMeta{Name: strings.Repeat("s", maxLength+1)},
+		&metav1.ObjectMeta{Name: "bad.name"},
+	}
+	for _, invalidMeta := range invalidMetas {
+		if err := validateObjectMetadata(invalidMeta); err == nil {
+			t.Errorf("Failed to validate object meta data: %s", err)
+		}
+	}
+}
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/metadata_validation_test.go]: wooot more coverage :D

File: pkg/apis/pipeline/v1alpha1/taskrun_types.go [hunk 4]
```diff
@@ -17,10 +17,19 @@ limitations under the License.
...
 	duckv1alpha1 "github.com/knative/pkg/apis/duck/v1alpha1"
+	"github.com/knative/pkg/webhook"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+// Check that Task may be validated and defaulted.
+var _ apis.Validatable = (*TaskRun)(nil)
+var _ apis.Defaultable = (*TaskRun)(nil)
+
+// Assert that Task implements the GenericCRD interface.
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_types.go]: i think the comments here should say `TaskRun` (or just "it" so we dont have to update it each time we copy it XD)

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+
+	return nil
+}
+
+func validateResultTarget(r ResultTarget, path string) *apis.FieldError {
+	// if result target is not set then do not error
+	var emptyTarget = ResultTarget{}
+	if r == emptyTarget {
+		return nil
+	}
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: This is completely outside the scope of your work so feel free to ignore me but i think maybe the results section should move into `status`.

In https://github.com/knative/build-pipeline/commit/9031ed4c5a585c09c1fcfc4341a5898eb0e25720#diff-b3fd75c449b28741c42f5ff5acc116ac I got a bit confused and removed it from the examples, since we are now requiring a reference to `PipelineParams` - but since the logs will be written to some subdir at those endpoints (probably) it's still useful to include them, however maybe the controller can decide the final location and report it in the status

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+	// If set then verify all variables pass the validation
+	if r.Name == "" {
+		return apis.ErrMissingField(fmt.Sprintf("%s.name", path))
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: im not sure what i think about checking that any field that is required and is a string isn't empty :thinking: one alternative would be to allow the usages to fail instead, seems a bit tedious to do this for every string field

on the other hand maybe it's always better to fail earlier?

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+	return nil
+}
+
+func checkForPipelineResourceDuplicates(resources []PipelineResourceVersion, path string) *apis.FieldError {
+	encountered := map[string]struct{}{}
+	for _, r := range resources {
+		// Check the unique combination of resource+version. Covers the use case of inputs with same resource name
+		// and different versions
+		key := fmt.Sprintf("%s%s", r.ResourceRef.Name, r.Version)
+		if _, ok := encountered[strings.ToLower(key)]; ok {
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/task_validation.go#L72 should probably be case insensitive also :thinking:

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 8]
```diff
@@ -0,0 +1,326 @@
...
+	"github.com/google/go-cmp/cmp"
+	"github.com/knative/pkg/apis"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+)
+
+func TestTaskRunValidate(t *testing.T) {
+	tests := []struct {
+		name string
+		task TaskRun
+		want *apis.FieldError
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: should we have a function with a success case too? e.g. `TestTaskRunValidate` and `TestTaskRunValidate_Invalid`

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 9]
```diff
@@ -0,0 +1,326 @@
...
+		},
+		{
+			name: "invalid taskrun metadata",
+			task: TaskRun{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: "task.name",
+				},
+			},
+			want: &apis.FieldError{
+				Message: "Invalid resource name: special character . must not be present",
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: what happens when you try to create an object like this directly via `kubectl`, does kubernetes itself catch this error?

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 10]
```diff
@@ -0,0 +1,326 @@
...
+				Paths:   []string{"metadata.name"},
+			},
+		},
+	}
+
+	for _, ts := range tests {
+		t.Run(ts.name, func(t *testing.T) {
+			err := ts.task.Validate()
+			if d := cmp.Diff(err.Error(), ts.want.Error()); d != "" {
+				t.Errorf("Validate/%s (-want, +got) = %v", ts.name, d)
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: ooo i like the `(-want, +got)`

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 11]
```diff
@@ -0,0 +1,326 @@
...
+			}
+		})
+	}
+}
+
+func TestTaskRunSpecValidate(t *testing.T) {
+	tests := []struct {
+		name    string
+		spec    *TaskRunSpec
+		wantErr *apis.FieldError
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: same thing, maybe a success case too?

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 12]
```diff
@@ -0,0 +1,326 @@
...
+			spec: &TaskRunSpec{
+				TaskRef: TaskRef{
+					Name: "taskrefname",
+				},
+				Trigger: TaskTrigger{
+					TriggerRef: TaskTriggerRef{
+						Type: TaskTriggerTypePipelineRun,
+					},
+				},
+			},
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: id rather have a separate test function completely for the success cases, i think it makes the tests much easier to understand (like I made @dlorenc do in https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/task_validation_test.go)

first reading this i actually didnt think there _were_ any success cases

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 13]
```diff
@@ -0,0 +1,326 @@
...
+		},
+		{
+			name: "valid task trigger run type",
+			spec: &TaskRunSpec{
+				TaskRef: TaskRef{
+					Name: "taskrefname",
+				},
+				Trigger: TaskTrigger{
+					TriggerRef: TaskTriggerRef{
+						Type: TaskTriggerTypePipelineRun,
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: if the type is `pipelinerun` there should be a `name` field as well with the name of the pipelinerun

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 14]
```diff
@@ -0,0 +1,326 @@
...
+						Name: "resultrunname",
+						Type: ResultTargetTypeGCS,
+						URL:  "",
+					},
+				},
+			},
+			wantErr: apis.ErrMissingField("spec.results.runs.URL"),
+		},
+		{
+			name: "valid task type result",
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: one idea to reduced the boilerplate in the testcases would be to test validation of the individual types in separate tests, e.g. have a set of tests just for `Results`, one just for `Inputs`, one just for `Params`, etc., then instead of having to instantiate an entire `TaskRun` each time, you could just instantiate the section you need to validate

**Comment by shashwathi** [comment]
@pivotal-nader-ziada @dlorenc : addressed your comments

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go [hunk 15]
```diff
@@ -0,0 +1,140 @@
...
+
+func (ts *TaskRunSpec) Validate() *apis.FieldError {
+	if equality.Semantic.DeepEqual(ts, &TaskRunSpec{}) {
+		return apis.ErrMissingField("spec")
+	}
+
+	// Check for TaskRef
+	if ts.TaskRef.Name == "" {
+		return apis.ErrMissingField("spec.taskref.name")
+	}
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: should we also validate that the referenced `Task` exists?

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 5 above)
Comment (bobcatfish) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: I should probably just create an issue for this :thinking:

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go (hunk 14 above)
Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: I did think about that but I am generally not a fan of testing private functions. Probably I could make `Validate` functions on each of the types and separate the cases. That might be lot easier to read.

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 5 above)
Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: Yeah lets make a separate issue for that 👍

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 6 above)
Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: That is the purpose for webhook validation, fail early to provide fast feedback about the object field validation.

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 15 above)
Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: For that kind of validation, pipeline client is required. In depth validation of related object existence could be done in taskrun controller.

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go (hunk 12 above)
Comment (shashwathi) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: Yeah that makes sense. I have updated tests to have clear distinction between valid and invalid test cases.

**Comment by shashwathi** [comment]
@bobcatfish : Addressed your comments. Let me know if there is anything else

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 15 above)
Comment (bobcatfish) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: ah interesting, okay good to know!

File: pkg/apis/pipeline/v1alpha1/taskrun_validation.go (hunk 6 above)
Comment (bobcatfish) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation.go]: kk!

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go (hunk 8 above)
Comment (bobcatfish) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: thanks!!

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go (hunk 12 above)
Comment (bobcatfish) [reply pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: sounds good, thanks @shashwathi !

File: pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go [hunk 16]
```diff
@@ -0,0 +1,378 @@
...
+	}
+	for _, ts := range tests {
+		t.Run(ts.name, func(t *testing.T) {
+			err := ts.outputs.Validate("spec.Outputs")
+			if d := cmp.Diff(err.Error(), ts.wantErr.Error()); d != "" {
+				t.Errorf("Validate/%s (-want, +got) = %v", ts.name, d)
+			}
+		})
+	}
+}
```
Comment (bobcatfish) [inline pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go]: <3 the tests!!

**Comment by bobcatfish** [comment]
I am happy to `/lgtm` - i think there's a conflict that has to get resolved first tho :weary:

**Comment by shashwathi** [comment]
@bobcatfish : Resolved the conflicts.

**Comment by pivotal-nader-ziada** [comment]
@bobcatfish I'm going to `lgtm` it since you said you are all good with it and now the conflicts are resolved

/lgtm
