### PR TITLE
Use dag execution instead of linear one

### LINKED ISSUE #168: Replace Pipeline linear execution with graph based execution
## Expected Behavior
Tasks in pipeline can run in parallel if:

* The inputs on which they run are available (via `from` field)
* The previous tasks (which should be indicated via `runAfter` - not yet in API, see [description of `runAfter` in design doc](https://docs.google.com/document/d/1RMnn_se_r29gVJ7ChLT_6oRhNeBnD7dfBg5vPUaVkbc/edit#heading=h.9p40gvk8rxtb) (_note doc visible to members of [knative-dev@googlegroups.com](https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md#build)_) 

## Actual Behavior
Right now, all Tasks execute linearly in the order they are defined in in the `Pipeline`

## Steps to Reproduce the Problem

Parallel case:
  1. Create Pipeline with 2 tasks which do not depend on each other
  2. Create a PipelineRun for this task
  3. Make sure they are executed in parallel

`from` case:
  1. Create Pipeline with 2 tasks , one which needs a resource `from` another, and declare them in the opposite order they should run in (i.e. put the Task the resource is `from` last)
  2. Create a PipelineRun for this task
  3. Make sure they are executed in the right order

`runAfter` case
  1. Create Pipeline with 2 tasks , one which is supposed to `runAfter` another and declare them in the opposite order they should run in (i.e. put the Task that should be`runAfter` last)
  2. Create a PipelineRun for this task
  3. Make sure they are executed in the right order

And combining these cases!

### PR DESCRIPTION
**Pull request by vdemeester**
Closes #168 

This switch `build-pipeline` to use the `dag` code for execution instead of the current linear behavior.

- update `dag` with a `GetSchedulable` task which returns the schedulable tasks
- fix `dag` false-positive cycle:
  The current DAG implementation was marking some graph as invalid even
  though they were. For example, the following DAG is valid.

  ```
           42
          /  \
       100    200
         \   / |
          101  |
            \  |
             102
  ```

  But the `dag.Build` would say there is a cycle in there. This is fixed
  by appending the visited node with the node currently "checked", that
  way, we can go through the same task twice, but from different path.
- use `dag.Build` and `dag.GetSchedulable` in the reconcilier
- It doesn't implement any [maximum number of parallel task](https://github.com/knative/build-pipeline/issues/168#issuecomment-458198492). We may want to create an issue for that and do that in a follow-up :angel: 

This is still a wip:

- [x] depends on #472
- [x] depends on #475
- [x] this might not be the best way to hook this up, looking for feedbacks :angel: 
- [x] let see how it breaks everything on the CI :sweat_smile: 
- [x] fully e2e tests (that actual assert something)
- [x] docs update
- [x] clean some unused code
- [x] add runafter
- [x] update examples
- [x] ~add webhook admission control validation~ created #559 

/cc @bobcatfish @tejal29

### CODE REVIEW

File: test/dag_test.go [hunk 1]
```diff
@@ -0,0 +1,219 @@
...
+	"time"
+
+	"github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1"
+	tb "github.com/knative/build-pipeline/test/builder"
+	knativetest "github.com/knative/pkg/test"
+	"github.com/knative/pkg/test/logging"
+)
+
+const (
+	// :((((((
```
Comment (bobcatfish) [inline test/dag_test.go]: :sweat_smile:

Comment (vdemeester) [reply test/dag_test.go]: @bobcatfish actually it's from your initial test, it should be quick now :stuck_out_tongue_closed_eyes:

**Comment by pivotal-nader-ziada** [comment]
@vdemeester do you think it's okay to squish some of the commits? seems some of them can be merged.

**Comment by vdemeester** [comment]
@pivotal-nader-ziada yes I definitely intend to squash them :wink: I just want to clean things a bit and I'll squash them when removing the `wip` label

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go [hunk 2]
```diff
@@ -93,6 +93,58 @@ func (g *DAG) GetPreviousTasks(pt string) []v1alpha1.PipelineTask {
 	return v.getPrevTasks()
 }
 
+// GetSchedulable returns a list of PipelineTask that can be scheduled,
+// given a list of "done" task.
```
Comment (bobcatfish) [inline pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: can you eleaborate here on what a 'list of done tasks' is? (i think `t` is a list of pipeline task names that have completed - successfully?)

**Comment by vdemeester** [comment]
> Do you think `Nodes map[string]*Node` is the best data structure to use going forward? We can totally iterate on this (esp. since it's an implementation detail the user will hopefully never notice :D) but I wonder if we could find a data structure that would hold the Pipeline Tasks in sorted order from the very beginning (i think @tejal29 suggested a topological sort?). I also think it could be v cool if we could run the "resolution" phase on this structure, such that very early in the reconciliation, we have a data structure that:
> 
>     1. holds the pipeline tasks in order (such that getting the next ones to run is just some kind of "pop" operation)
> 
>     2. has resolved all of the references in the pipeline tasks

Most likely yes — it's definitely not "optimized", but I'm not sure of the level of optimization we need yet :stuck_out_tongue_closed_eyes: The `map` is only used to quickly be able to look is a task is present or not (the map could even be `map[string]struct{}` I think to take less memory).



>     * There are a couple of functions which could probably use their own unit tests: `GetSchedulable`, `GetPreivousTasks` innocent

Yes, `GetSchedulable` already has its tests but the test is… incorrectly named :man_facepalming:

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go (hunk 2 above)
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: Yes, indeed, it will be successful tasks here (only) as if one fails, the pipeline will be marked failed and the taskruns too. I should also rename the variables :sweat_smile:

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go [hunk 3]
```diff
@@ -299,20 +310,22 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1alpha1.PipelineRun) er
 	}
 
 	serviceAccount := pr.Spec.ServiceAccount
-	rprt := resources.GetNextTask(pr.Name, pipelineState, c.Logger)
+	rprts := resources.GetNextTasks(pr.Name, d, pipelineState, c.Logger)
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: There is definitely some duplication between the two, and I feel like they should be "the same" at some point. Didn't want to go that path yet (as I wanted to keep the changeset small) but this is definitely something to lean forward to.

**Comment by bobcatfish** [comment]
> Most likely yes — it's definitely not "optimized", but I'm not sure of the level of optimization we need yet

haha kk, sorry for trying to optimize prematurely XD - definitely easier to iterate on this once we get an initial implementation in :)

File: pkg/reconciler/v1alpha1/pipeline/resources/dag_test.go [hunk 4]
```diff
@@ -96,28 +123,47 @@ func TestBuild(t *testing.T) {
...
+		}, {
+			name: "no-cycle",
+			spec: v1alpha1.PipelineSpec{Tasks: []v1alpha1.PipelineTask{a, dDependsOnA, eDependsOnA, fDependsOnDAndE, gDependOnF}},
+			expectedDAG: &DAG{
+				Nodes: map[string]*Node{
+					"a": {Task: a},
+					"d": {Task: dDependsOnA, Prev: []*Node{{Task: a}}},
+					"e": {Task: eDependsOnA, Prev: []*Node{{Task: a}}},
+					"f": {Task: fDependsOnDAndE, Prev: []*Node{{Task: dDependsOnA, Prev: []*Node{{Task: a}}}, {Task: eDependsOnA, Prev: []*Node{{Task: a}}}}},
+					"g": {Task: gDependOnF, Prev: []*Node{{Task: fDependsOnDAndE, Prev: []*Node{{Task: dDependsOnA, Prev: []*Node{{Task: a}}}, {Task: eDependsOnA, Prev: []*Node{{Task: a}}}}}}},
```
Comment (bobcatfish) [inline pkg/reconciler/v1alpha1/pipeline/resources/dag_test.go]: do you think it would be crazy to have some comments that try to depict the graphs in these tests? :innocent:

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: kk sounds reasonable! :D

**Comment by vdemeester** [comment]
Cleaned a bit and rebased, there is still work to do on the `e2e` tests though :sweat_smile:

**Comment by bobcatfish** [comment]
Okay I still need to:

- rebase
- add webhook admission validation
- update the examples

But the bulk of the changes are here so PTAL :D

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go [hunk 5]
```diff
@@ -47,31 +49,31 @@ const (
...
-				logger.Infof("TaskRun %s has failed; we don't need to run PipelineRun %s", prtr.TaskRunName, prName)
-				return nil
-			case corev1.ConditionUnknown:
-				logger.Infof("TaskRun %s is still running so we shouldn't start more for PipelineRun %s", prtr.TaskRunName, prName)
-				return nil
+		}
+	}
+	toSchedule, err := d.GetSchedulable(done...)
+	if err != nil {
+		return tasks, fmt.Errorf("somehow the list of done tasks %v is invalid: %v", done, err)
```
Comment (shashwathi) [inline pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go]: Better error msg. 
just a suggestion: `Error getting schedulable tasks`

**Comment by bobcatfish** [comment]
@vdemeester ive pushed all of my changes, not sure if you're working next week or not, but most of us are out Monday. feel free to pick this up again if you want, otherwise i can resume on tuesday :D

**Comment by vdemeester** [comment]
@bobcatfish rebased :angel: there is a unit tests that fails, I'll see why :angel:

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go [hunk 6]
```diff
@@ -84,13 +95,99 @@ func getVisitedPath(path []string) string {
...
+		d = append(d, schedulable...)
+	}
+
+	visitedNames := make([]string, len(visited))
+	for v := range visited {
+		visitedNames = append(visitedNames, v)
+	}
+
+	notVisited := list.DiffLeft(doneTasks, visitedNames)
+	if len(notVisited) > 0 {
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: @shashwathi we could, but I feel it's a bit more readable like that :angel:

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go [hunk 7]
```diff
@@ -84,13 +95,99 @@ func getVisitedPath(path []string) string {
...
+func toMap(t ...string) map[string]struct{} {
+	m := make(map[string]struct{}, len(t))
+	for _, s := range t {
+		m[s] = struct{}{}
+	}
+	return m
+}
+
+func addLink(pt v1alpha1.PipelineTask, previousTask string, d *DAG) error {
+	prev, ok := d.Nodes[previousTask]
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: @shashwathi it seems, it requires the pointer because `linkPipelineTasks` has the pointer as a receiver… That said, `linkPipelineTasks` doesn't need or use `DAG` anyway, so we could refactor this a bit, looking into it :eyes:

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go [hunk 8]
```diff
@@ -209,6 +210,18 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1alpha1.PipelineRun) er
 
 	p = p.DeepCopy()
 
+	d, err := dag.Build(p)
+	if err != nil {
+		// This Run has failed, so we need to mark it as failed and stop reconciling it
+		pr.Status.SetCondition(&duckv1alpha1.Condition{
+			Type:   duckv1alpha1.ConditionSucceeded,
+			Status: corev1.ConditionFalse,
+			Reason: ReasonInvalidBindings,
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: @shashwathi good point :+1:

**Comment by bobcatfish** [comment]
```
I0226 14:24:19.881] =============================
I0226 14:24:19.881] ==== RUNNING BUILD TESTS ====
I0226 14:24:19.881] =============================
I0226 14:24:19.887] ------------------------------------
I0226 14:24:19.887] ---- Linting the markdown files ----
I0226 14:24:19.887] ------------------------------------
I0226 14:24:22.544] /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl/rules.rb:588:in `block (3 levels) in load': undefined method `match' for nil:NilClass (NoMethodError)
I0226 14:24:22.545] Did you mean?  catch
I0226 14:24:22.545] 	from /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl/rules.rb:583:in `each'
I0226 14:24:22.545] 	from /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl/rules.rb:583:in `block (2 levels) in load'
I0226 14:24:22.545] 	from /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl.rb:86:in `block (2 levels) in run'
I0226 14:24:22.546] 	from /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl.rb:84:in `each'
I0226 14:24:22.546] 	from /var/lib/gems/2.3.0/gems/mdl-0.5.0/lib/mdl.rb:84:in `block in run'
```

oh boy

**Comment by bobcatfish** [comment]
It looks like we literally hit this exact error: https://github.com/markdownlint/markdownlint/issues/211 The linting tool can't handle links with bolding around them.

(Which has been fixed in the codebase but they haven't made a new release yet :thinking: )

I'll just change the formatting for now, and I'm going to do it in a separate PR.

**Comment by bobcatfish** [comment]
image

**Comment by bobcatfish** [comment]
Fixing linting issue in https://github.com/knative/build-pipeline/pull/554

**Comment by bobcatfish** [comment]
> * `GetSchedulable` is the main function to interface from reconciler so why not return a map of pipeline task names. It would become simple code in reconciler `GetNextTasks`

Good call @shashwathi , updated!

**Comment by bobcatfish** [comment]
Okay @vdemeester everything is done i think except for the webhook validation! I could even see doing that in another PR :woman_shrugging:

**Comment by bobcatfish** [comment]
hm looks like some of our test coverage went down - im going to see what i can do to fix that!

**Comment by bobcatfish** [comment]
> @bobcatfish agreeing, we can make a follow-up for the validation part

kk, created #559 for that!

**Comment by bobcatfish** [comment]
Okay coverage diffs look a bit more reasonable now, PTAL @shashwathi @pivotal-nader-ziada  :tada:

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go [hunk 9]
```diff
@@ -21,9 +21,19 @@ import (
 	"strings"
 
 	"github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1"
-	errors "github.com/knative/build-pipeline/pkg/errors"
+	"github.com/knative/build-pipeline/pkg/reconciler/v1alpha1/taskrun/list"
```
Comment (pivotal-nader-ziada) [inline pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: the files in `pipelineRun` reconciler should not be using functions from `taskRun` reconciler. The `list` package should be extracted out

File: pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go [hunk 10]
```diff
@@ -522,7 +522,7 @@ func TestAddResourceToBuild(t *testing.T) {
 		wantErr: false,
 		want: buildv1alpha1.BuildSpec{
 			Steps: []corev1.Container{{
-				Name:  "create-dir-workspace-mz4c7",
+				Name:  "create-dir-workspace-0-0-mz4c7",
```
Comment (pivotal-nader-ziada) [inline pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go]: why is this `0-0` added? container name should not have changed by this feature

File: test/README.md [hunk 11]
```diff
@@ -147,13 +147,13 @@ export GCP_SERVICE_ACCOUNT_KEY_PATH="$PWD/config.json"
...
-Integration tests live in this directory. To run these tests, you must provide
+End to end tests live in this directory. To run these tests, you must provide
 `go` with `-tags=e2e`. By default the tests run against your current kubeconfig
 context, but you can change that and other settings with [the flags](#flags):
 
 ```shell
-go test -v -count=1 -tags=e2e ./test
-go test -v -tags=e2e -count=1 ./test --kubeconfig ~/special/kubeconfig --cluster myspecialcluster
+go test -v -count=1 -tags=e2e -timeout=20m ./test
+go test -v -count=1 -tags=e2e -timeout=20m ./test --kubeconfig ~/special/kubeconfig --cluster myspecialcluster
```
Comment (pivotal-nader-ziada) [inline test/README.md]: I believe tests e2e tests already take more then 20m and growing, can we change it to 30

Comment (shashwathi) [reply test/README.md]: They are all running in parallel so adding more tests should not result in 10m increase of test timing.

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go (hunk 9 above)
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: @pivotal-nader-ziada hum good point :thinking: I think `taskrun/list` package should be extracted in a upper package (as it really doesn't depend on `taskrun`).
@bobcatfish agreeing ? (I can take care of it :wink:)

File: pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go (hunk 10 above)
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go]: This is related to the following item of the commit message
```
Make sure `create-dir` containers gets a unique name (the same way `copy-` containers do)
```

File: test/README.md (hunk 11 above)
Comment (vdemeester) [reply test/README.md]: :sweat:

Comment (pivotal-nader-ziada) [reply test/README.md]: They already take about 25m
https://gubernator.knative.dev/builds/knative-prow/pr-logs/pull/knative_build-pipeline/473/pull-knative-build-pipeline-integration-tests/

File: pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go (hunk 10 above)
Comment (pivotal-nader-ziada) [reply pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go]: but they have a random string appended to them, why do we need the index?

File: pkg/reconciler/v1alpha1/pipeline/resources/dag.go (hunk 9 above)
Comment (pivotal-nader-ziada) [reply pkg/reconciler/v1alpha1/pipeline/resources/dag.go]: makes sense @vdemeester

File: pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go (hunk 10 above)
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/taskrun/resources/input_resource_test.go]: @pivotal-nader-ziada ah good point, that was done "before" we had that random string… :sweat_smile: We should remove that then :angel:

**Comment by pivotal-nader-ziada** [comment]
looks good, thanks for the changes @vdemeester 

/lgtm
