### PR TITLE
Get simple PipelineRun implementation working

### LINKED ISSUE #61: Implement simple PipelineRun
## Expected Behavior
A user should be able to create a `PipelineRun` which will look at the `Tasks` in the referenced `Pipeline` and for each of those, create a `TaskRun`.

If #59 is done before this, creation of the `TaskRun` would also trigger running of the `Task`, however if not, nothing would actually be executed but the `TaskRuns` would exist.

Out of scope of this issue (coming in later issues):
* Providing inputs to the Tasks
* Doing something with produced outputs

Requirements:
* Test coverage (unit tests + if possible integration tests, may be blocked by #16 )
* Docs that explain how to create a PipelineRun, with examples
* Docs that explain how to debug this (i.e. where to look if it goes wrong)

## Actual Behavior
If you create a `PipelineRun`, nothing will happen.

## Steps to Reproduce the Problem

  1. Deploy the Pipeline CRD + related CRDs to your cluster (note: should be docs on how to do this post kubebuilder)
  2. Create a `Task` like this:
```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: helloworld-task
  namespace: default
spec:
    buildSpec:
        steps:
            - name: helloworld
              image: busybox
              args: ['echo', 'hello', 'build']
```
  3. Create a `Pipeline` like this:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
  namespace: default
spec:
    tasks:
        - name: helloworld-task-1
          taskRef:
              name: helloworld-task
        - name: helloworld-task-2
          taskRef:
              name: helloworld-task
        - name: helloworld-task-3
          taskRef:
              name: helloworld-task
```

4. Create a `PipelineRun` like this:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pipeline-run-1
  namespace: default
spec:
    pipelineRef:
        name: hello-pipeline
    triggerRef:
        type: manual
```

5. Creating the PipelineRun should have created `TaskRuns`, so we should then be able to see:

  a. The `status` of the `PipelineRun` should be updated (see [example](https://github.com/knative/build-pipeline/blob/master/examples/invocations/kritis-pipeline-run.yaml#L27)), check with `kubectl get pipelineRuns`
  b. There should be 3 `TaskRuns` created, each with a unique name and a reference to the `PipelineRun` (check with `kubectl get taskRuns`), for example:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: TaskRun
metadata:
  name: helloworld-task-run-1-1
spec:
    taskRef:
        name: helloworldTask
    trigger:
        triggerRef:
            type: manual
```

(I left the PipelineParams reference out of the PipelineRun, but if it turns out that we need a ServiceAccount to make this work, we'll need to specify it in the PipelineParams and reference it in the PipelineRun as well)

### PR DESCRIPTION
**Pull request by bobcatfish**
Sorry this is a big one, with even more refactoring 😅The net effect is that when we create a PipelineRun, it actually creates and executes the required Task runs! 🎉 

I tried to break it up into separate commits, so might be easier to review that way:

1. Combine logic to grab Tasks and their Runs for a PipelineRun

    It turns out that we need to look at TaskRuns for a few reasons, including 1) figuring out what to run next and 2) determining the status of the PipelineRun, so I've refactored the logic that grabs these to collect a bunch of related state that can be reused. When the graph becomes more sophisticated, we will need to make this structure more than just a list.
2. Check status of TaskRuns when finding TaskRun to start
    Added logic to check statuses of other TaskRuns when deciding if a new one should be started for #61
3. Add condition status to PipelineRun
    PipelineRun status will be based on the condition of the TaskRuns which it has created, for #61. If any TaskRuns have failed, the PipelineRun has failed. If all are successful, it is successful. If any are in progress, it is in progress. This is assuming a linear Pipeline, we will have to tweak this a bit
when we implement the graph (for #65)
4. Create TaskRun from PipelineRun that runs a Task Added the Task reference to the TaskRun so that when a PipelineRun creates a TaskRun, it actually executes! (For #61)
    While running the integration test, noticed that the PipelineRuns weren't getting reconciled quickly enough, but adding a tracker which will invoke reconcile when the created TaskRuns are updated fixed this - however it did still take > 1 minute to create 3 helloworld TaskRuns and wait for them to complete, so since 3 was arbitrary, reduced to 2. Also cleaned up the TaskRun controller a bit: using the Logger object on the controller/reconciler itself, made the log messages a bit more descriptive.

Fixes #61

### CODE REVIEW

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go [hunk 1]
```diff
@@ -134,39 +154,36 @@ func (c *Reconciler) Reconcile(ctx context.Context, key string) error {
...
+		},
 		func(namespace, name string) (*v1alpha1.TaskRun, error) {
 			return c.taskRunLister.TaskRuns(namespace).Get(name)
 		},
-		p, pr.Name)
+		p, pr.Name,
+	)
 	if err != nil {
-		return fmt.Errorf("error getting next TaskRun to create for PipelineRun %s: %s", pr.Name, err)
+		return fmt.Errorf("error getting Tasks for Pipeline %s, Pipeline may be invalid!: %s", p.Name, err)
```
Comment (tejal29) [inline pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: s/error getting Tasks for Pipeline/error getting Tasks or TaskRuns for Pipeline/

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+	PipelineTask *v1alpha1.PipelineTask
+	TaskRunName  string
+	TaskRun      *v1alpha1.TaskRun
+}
+
+// GetTask is a function that will retrieve the Task name from namespace.
+type GetTask func(namespace, name string) (*v1alpha1.Task, error)
+
+// GetTaskRun is a function that will retrieve the TaskRun name from namespace.
+type GetTaskRun func(namespace, name string) (*v1alpha1.TaskRun, error)
```
Comment (tejal29) [inline pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: Not your fault, but this is not rendered properly :) i wonder if its a formatting issue

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+// Task using getTaskRun (the name is built from pipelineRunName). If it is unable to
+// retrieve an instance of a referenced Task, it will return an error, otherwise it
+// returns a list of all of the Tasks retrieved, and their TaskRuns if applicable.
+func GetPipelineState(getTask GetTask, getTaskRun GetTaskRun, p *v1alpha1.Pipeline, pipelineRunName string) ([]*PipelineRunTaskRun, error) {
+	state := []*PipelineRunTaskRun{}
+	for i := range p.Spec.Tasks {
+		pt := p.Spec.Tasks[i]
+		t, err := getTask(p.Namespace, pt.TaskRef.Name)
+		if err != nil {
+			return nil, fmt.Errorf("failed to get tasks for Pipeline %q: Error getting task %q : %s",
```
Comment (tejal29) [inline pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: Now, this is case where we need to check if Task does not exists.
If it does not exist, then we should quit re-conciling this pipeline since its invalid and nothing can be done.  
For that to happen, we should return "nil" from the `pipelinerun.Reconciler.reconcile`

however, there was some other error while fetching task then we keep trying. 
Does that make sense? 

I would say, we can create a InvalidPipelineError and return that from here when a Task is not found.
In the `reconcile` method, we should if err is something other than InvalidPipelineError and return nil if its InvalidPipelineError

File: pkg/apis/pipeline/v1alpha1/pipelinerun_types.go [hunk 4]
```diff
@@ -71,7 +71,22 @@ type PipelineRunStatus struct {
 	// If there is no version, that means use latest
 	// +optional
 	ResourceVersion []PipelineResourceVersion `json:"resourceVersion,omitempty"`
-	Conditions      []PipelineRunCondition    `json:"conditions"`
+	Conditions      duckv1alpha1.Conditions   `json:"conditions"`
+}
+
+var pipelineRunCondSet = duckv1alpha1.NewBatchConditionSet()
```
[the remark this answers is not in the document]
Comment (tejal29) [reply pkg/apis/pipeline/v1alpha1/pipelinerun_types.go]: hmm this is not the types i was thinking about.

File: test/pipelinerun_test.go [hunk 5]
```diff
@@ -50,17 +51,30 @@ func TestPipelineRun(t *testing.T) {
...
-		t.Errorf("Error waiting for TaskRun %s to finish: %s", hwTaskRunName, err)
+	}, "PipelineRunSuccess"); err != nil {
+		t.Errorf("Error waiting for PipelineRun %s to finish: %s", hwTaskRunName, err)
 	}
 
-	// TODO check that TaskRuns created
+	logger.Infof("Making sure the expected TaskRuns were created")
+	expectedTaskRuns := []string{
+		hwPipelineName + hwPipelineTaskName1,
+		hwPipelineName + hwPipelineTaskName2,
```
Comment (bobcatfish) [inline test/pipelinerun_test.go]: whoops somehow forgot to include a fix for this

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go (hunk 2 above)
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: yeah im not sure why the syntax highlighting is having a problem here :thinking: 

last time I saw this happen it was b/c @jonjohnsonjr decided to replace a `e` with an `ℯ` or something like that

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go (hunk 1 above)
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: good call!

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go (hunk 2 above)
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: ah that could be it, thanks @jonjohnsonjr :D

and seriously that `𝛾` was pretty sweet, gonna be talking about that one for years to come

Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: https://github.com/knative/serving/pull/1460#discussion_r199993007

:rofl:

Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: image

oh it just keeps getting better, i'm crying

Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: well that was distracing

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go (hunk 3 above)
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinestate.go]: yep that makes sense! okay ill update this so that if we can't find a task, we return nil from the reconcile loop and stop reconciling.

thanks for catching this and the detailed explanation!

**Comment by bobcatfish** [comment]
Ready for another look @tejal29 !

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go [hunk 6]
```diff
@@ -91,6 +95,11 @@ func NewController(
 		UpdateFunc: controller.PassNew(impl.Enqueue),
 		DeleteFunc: impl.Enqueue,
 	})
+
+	r.tracker = tracker.New(impl.EnqueueKey, 30*time.Second)
```
Comment (pivotal-nader-ziada) [inline pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: I added a better way to get the tracker lease as a function of the resync period in #120 which I can update here once this is merged, no point in both of us making the same change

**Comment by bobcatfish** [comment]
oh dear

```
I1012 01:29:35.122] default                  8s          8s           1         pvc-284c1005-cdbe-11e8-a9ba-42010a800231.155cb8422d54da43                         PersistentVolume                                                Normal    VolumeDelete              persistentvolume-controller                                           googleapi: Error 400: The disk resource 'projects/knative-boskos-10/zones/us-central1-a/disks/gke-kbuild-pipeline-e2-pvc-284c1005-cdbe-11e8-a9ba-42010a800231' is already being used by 'projects/knative-boskos-10/zones/us-central1-a/instances/gke-kbuild-pipeline-e2e--default-pool-a626184b-8p1m', resourceInUseByAnotherResource
```

File: pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go]: nice!! thanks @pivotal-nader-ziada :D if you merge first ill pickup your change, ill leave this at 30 min for now then

**Comment by bobcatfish** [comment]
oh i guess that volume error is about deletion, maybe a red herring 🤔

**Comment by bobcatfish** [comment]
```
I1012 01:29:21.113] --- FAIL: TestPipelineRun (240.28s)
I1012 01:29:21.113] 	pipelinerun_test.go:63: Error waiting for PipelineRun helloworld-run to finish: timed out waiting for the condition
I1012 01:29:21.113] 	pipelinerun_test.go:77: Expected TaskRun helloworld-pipelinerun-helloworld-task-1 to have succeeded but Status is Unknown
I1012 01:29:21.113] 	pipelinerun_test.go:73: Couldn't get expected TaskRun helloworld-pipelinerun-helloworld-task-2: taskruns.pipeline.knative.dev "helloworld-pipelinerun-helloworld-task-2" not found
I1012 01:29:21.114] 	crd.go:237: Error waiting for Pod helloworld-validation-busybox to finish: timed out waiting for the condition
````
yyyyyyyyyyyyyyyyyyyyyyyy

**Comment by bobcatfish** [comment]
oh man i just keep making these tests better and better XD

``
I1012 16:40:42.177] --- FAIL: TestTaskRun (0.06s)
I1012 16:40:42.178] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
I1012 16:40:42.178] 	panic: runtime error: invalid memory address or nil pointer dereference
I1012 16:40:42.178] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x152ab9b]
I1012 16:40:42.178] 
I1012 16:40:42.178] goroutine 166 [running]:
I1012 16:40:42.178] testing.tRunner.func1(0xc4200ac2d0)
I1012 16:40:42.178] 	/usr/local/go/src/testing/testing.go:742 +0x567
I1012 16:40:42.178] panic(0x163b020, 0x20b1ce0)
I1012 16:40:42.178] 	/usr/local/go/src/runtime/panic.go:502 +0x24a
I1012 16:40:42.178] github.com/knative/build-pipeline/test.TestTaskRun.func2(0xc4202886c0, 0x17789c3, 0xe, 0x0)
I1012 16:40:42.179] 	/go/src/github.com/knative/build-pipeline/test/taskrun_test.go:56 +0x7b
I1012 16:40:42.179] github.com/knative/build-pipeline/test.WaitForTaskRunState.func1(0x94e27f, 0x1, 0xc4205a6800)
I1012 16:40:42.179] 	/go/src/github.com/knative/build-pipeline/test/crd_checks.go:54 +0x152
I1012 16:40:42.179] github.com/knative/build-pipeline/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc4205a6800, 0xc4202262d0, 0xc4205a6800, 0x16af140)
I1012 16:40:42.179] 	/go/src/github.com/knative/build-pipeline/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:245 +0x39
I1012 16:40:42.179] github.com/knative/build-pipeline/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x3b9aca00, 0x1bf08eb000, 0xc4202262d0, 0x31, 0x0)
I1012 16:40:42.179] 	/go/src/github.com/knative/build-pipeline/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:241 +0x5f
I1012 16:40:42.180] github.com/knative/build-pipeline/test.WaitForTaskRunState(0xc42011f260, 0x17789c3, 0xe, 0x17ed5a0, 0x177881f, 0xe, 0x0, 0x0)
I1012 16:40:42.180] 	/go/src/github.com/knative/build-pipeline/test/crd_checks.go:49 +0x320
I1012 16:40:42.180] github.com/knative/build-pipeline/test.TestTaskRun(0xc4200ac2d0)
I1012 16:40:42.180] 	/go/src/github.com/knative/build-pipeline/test/taskrun_test.go:54 +0xf37
I1012 16:40:42.180] testing.tRunner(0xc4200ac2d0, 0x17ed5a8)
I1012 16:40:42.180] 	/usr/local/go/src/testing/testing.go:777 +0x16e
I1012 16:40:42.180] created by testing.(*T).Run
I1012 16:40:42.180] 	/usr/local/go/src/testing/testing.go:824 +0x565
I1012 16:40:42.181] FAIL	github.com/knative/build-pipeline/test	118.710s
```

**Comment by bobcatfish** [comment]
image

:weary:

**Comment by bobcatfish** [comment]
:crossed_fingers::crossed_fingers::crossed_fingers: 
image
:crossed_fingers::crossed_fingers::crossed_fingers:

**Comment by bobcatfish** [comment]
:weary:

**Comment by bobcatfish** [comment]
/lgtm

WHAT ITS WORTH A TRY

**Comment by bobcatfish** [comment]
image

image
