### PR TITLE
Run integration tests on presubmit using boskos (from prow) or kubetest (locally) or an existing cluster

### LINKED ISSUE #16: Setup PR testing for build-pipeline integration tests
_Need to complete #15 before we can tackle this_

## Expected Behavior
Every PR should have integration tests run against it automatically.

(The long term dream is that we use the Pipeline CRD reference implementation _itself_ to test this repo, but since it is just an API right now, that's a ways off!)

## Actual Behavior
Even once #15 is done, we won't have anything to ensure we can actually deploy the CRDs and use them with a running controller.

## Steps to Reproduce the Problem

To run the current equivalent of "integration tests",  manually walk through [the "installing and running" steps in the DEVELOPMENT.md](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running):

```bash
# Add/update CRDs in your kubernetes cluster
make install

# Run your controller locally, (stop execution with `ctrl-c`)
make run

# In another terminal, deploy tasks
kubectl apply -f config/samples
```

## Additional Info

We'll need a k8s cluster to deploy to, probably we can make use of [boskos](https://github.com/kubernetes/test-infra/tree/master/boskos#boskos):
* [knative boskos configuration](https://github.com/knative/test-infra/tree/master/ci/prow/boskos)
* I _think_ knative uses boskos [by way of kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest#dynamic-project-selection) but I'm not sure exactly how that is working

Whatever we implement should be easy for contributors to trigger manually and not require specific credentials.

### PR DESCRIPTION
**Pull request by bobcatfish**
Using the scripts from knative/test-infra, run the integration tests
against a cluster created with boskos. A lot of the boskos stuff is
still kind of magical, for example I have no idea what is controlling
the $PROJECT_ID that is being used by knative projects on presubmit, but
after wrestling with it a bit and hacking around `--run-tests` I was
able to get it to work locally and deploy a cluster (I assume using
boskos?). I'll follow up on this more later on and update the docs when
I have more info.

Assuming we can get https://github.com/knative/test-infra/pull/169
merged I'll revert the change to `e2e-tests.sh` in the `vendor` dir.

Fixes #16

### CODE REVIEW

File: test/cluster-setup.sh [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+}
+
+set +o xtrace
+header "Setting up environment"
+# The intialize method will attempt to create a new cluster in $PROJECT_ID unless
+# the `--run-tests` parameter is provided and `K8S_CLUSTER_OVERRIDE` is set, however
+# since knative/test-infra/scripts/presubmit-tests.sh doesn't propagate `--run-tests`
+# (and it's kind of a confusing param name), we'll infer it from the presence of
+# `K8S_CLUSTER_OVERRIDE`
+if [[ -z ${K8S_CLUSTER_OVERRIDE} ]]; then
```
Comment (adrcunha) [inline test/cluster-setup.sh]: You don't need this. This is all handled by the helper.
See the most simple E2E script there is:

https://github.com/knative/test-infra/blob/master/test/e2e-tests.sh

It's so simple that the number of comment lines is much greater than the number of actual code lines. :D

The header of the helper should contain all the instructions about writing your own script.

File: test/cluster-setup.sh [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+else
+    initialize --run-tests
+fi
+set -o xtrace
+
+# The scripts were initially setup to use the knative/serving style `DOCKER_REPO_OVERRIDE`
+# before knative/serving was updated to use `ko` + `KO_DOCKER_REPO`. If the scripts were
+# called with `KO_DOCKER_REPO` already set (i.e. using a user's own local cluster, we should
+# respect that).
+if ! [[ -z ${DOCKER_REPO_OVERRIDE} ]]; then
```
Comment (adrcunha) [inline test/cluster-setup.sh]: `DOCKER_REPO_OVERRIDE` will be set by the helper, no need to check.

File: test/cluster-setup.sh [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+# Deploy the latest version of the Pipeline CRD.
+# TODO(#59) do we need to deploy the Build CRD as well?
+header "Deploying Pipeline CRD"
+ko apply -f config/
+
+# Wait for pods to be running in the namespaces we are deploying to
+set +o xtrace
+wait_until_pods_running knative-build-pipeline || fail_test "Pipeline CRD did not come up"
+set -o xtrace
```
Comment (adrcunha) [inline test/cluster-setup.sh]: End with `success` otherwise your test will always report failure no matter what.

File: test/init_test.go [hunk 4]
```diff
@@ -73,6 +73,7 @@ func tearDownMain(kubeClient *knativetest.KubeClient, logger *logging.BaseLogger
 func TestMain(m *testing.M) {
 	initializeLogsAndMetrics()
 	logger := logging.GetContextLogger("TestMain")
+	logger.Infof("Using kubeconfig at `%s` with cluster `%s`", knativetest.Flags.Kubeconfig, knativetest.Flags.Cluster)
 
 	namespace = AppendRandomString("arendelle")
```
Comment (adrcunha) [inline test/init_test.go]: My daughter loved this line of code. :)

File: test/presubmit-tests.sh [hunk 5]
```diff
@@ -15,6 +15,9 @@
 # limitations under the License.
 
 # This script runs the presubmit tests; it is started by prow for each PR.
+# When running `--integration-tests`, use `K8S_CLUSTER_OVERRIDE` to point at your
```
Comment (adrcunha) [inline test/presubmit-tests.sh]: As explained, this is not true, remove.

File: vendor/github.com/knative/test-infra/scripts/e2e-tests.sh [hunk 6]
```diff
@@ -47,11 +47,11 @@ source $(dirname ${BASH_SOURCE})/library.sh
 function build_resource_name() {
   local prefix=${E2E_BASE_NAME}-$1
   local suffix=${BUILD_NUMBER}
-  # Restrict suffix length to 20 chars
+  # Restrict suffix length to 30 chars
```
Comment (adrcunha) [inline vendor/github.com/knative/test-infra/scripts/e2e-tests.sh]: As I mentioned in the other PR, this is not necessary.

File: test/cluster-setup.sh [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+# The scripts were initially setup to use the knative/serving style `DOCKER_REPO_OVERRIDE`
+# before knative/serving was updated to use `ko` + `KO_DOCKER_REPO`. If the scripts were
+# called with `KO_DOCKER_REPO` already set (i.e. using a user's own local cluster, we should
+# respect that).
+if ! [[ -z ${DOCKER_REPO_OVERRIDE} ]]; then
+    export KO_DOCKER_REPO=${DOCKER_REPO_OVERRIDE}
+fi
+
+# Deploy the latest version of the Pipeline CRD.
+# TODO(#59) do we need to deploy the Build CRD as well?
```
Comment (pivotal-nader-ziada) [inline test/cluster-setup.sh]: I think we should deploy build CRD as part of this setup, check #88

**Comment by bobcatfish** [comment]
oooo

```
W1003 17:51:45.917] Error from server (Forbidden): error when deleting "config/100-namespace.yaml": namespaces "knative-build-pipeline" is forbidden: User "system:serviceaccount:test-pods:default" cannot delete namespaces in the namespace "knative-build-pipeline": Unknown user "system:serviceaccount:test-pods:default
```

**Comment by bobcatfish** [comment]
oh noes, something went wrong even before that, looks like that my naiive truncation fix was a bit too naiive! https://github.com/knative/test-infra/pull/169

```
W1003 17:51:42.859] ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Cluster.name must be less than 40 characters.
W1003 17:51:42.923] 2018/10/03 17:51:42 process.go:155: Step 'gcloud container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --enable-basic-auth --no-issue-client-certificate --project=knative-boskos-01 --zone=us-central1-a --machine-type=n1-standard-4 --image-type=cos --num-nodes=3 --network=kbuild-pipeline-e2e-net1047544414697689088 --cluster-version=1.10.7 kbuild-pipeline-e2e-cls1047544414697689088' finished in 567.454918ms
W1003 17:51:43.865] 2018/10/03 17:51:43 main.go:309: Something went wrong: starting e2e cluster: error creating cluster: error during gcloud container clusters create
```

File: test/README.md [hunk 8]
```diff
@@ -127,4 +127,29 @@ You can run this locally with:
...
+`K8S_CLUSTER_OVERRIDE` environment variable to force the scripts to use your own cluster,
+and provide `KO_DOCKER_REPO` (as specified in the [DEVELOPMENT.md](../DEVELOPMENT.md#environment-setup)):
+
+```shell
+export K8S_CLUSTER_OVERRIDE=my_k8s_cluster # corresponds to a `context` in your kubeconfig
+export KO_DOCKER_REPO=gcr.io/my_docker_repo # required for deployments using `ko`
+test/presubmit-tests.sh --integration-tests
+```
+
+Otherwise, the script will attempt to use [boskos](https://github.com/kubernetes/test-infra/tree/master/boskos)
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/README.md]: what does the helper use to deploy clusters when running locally?

File: test/cluster-setup.sh [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+
+set -o xtrace
+set -o errexit
+set -o pipefail
+
+function take_down_pipeline() {
+    header "Tearing down Pipeline CRD"
+    ko delete --ignore-not-found=true -f config/
+}
+trap take_down_pipeline EXIT
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/cluster-setup.sh]: unfortunately when running locally, the helper script will invoke `teardown` _before_ running anything, which against a pre-existing cluster caused the subsequent deployment to sometimes fail because during the deployment, we would try to deploy to namespaces that were in the process of being terminated

(ill add a comment!)

File: test/README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/README.md]: maybe it's kubetest that's doing the deployment? (is kubetest using boskos underneath?)

this is in the case where:
1. I'm running the script locally
2. I'm not using a predefined cluster, but I have `$PROJECT_ID` set

File: test/README.md [hunk 10]
```diff
@@ -127,4 +127,29 @@ You can run this locally with:
...
+have access to.
+
+If you would like to run the integration tests against your cluster, you can use the
+`K8S_CLUSTER_OVERRIDE` environment variable to force the scripts to use your own cluster,
+and provide `KO_DOCKER_REPO` (as specified in the [DEVELOPMENT.md](../DEVELOPMENT.md#environment-setup)):
+
+```shell
+export K8S_CLUSTER_OVERRIDE=my_k8s_cluster # corresponds to a `context` in your kubeconfig
+export KO_DOCKER_REPO=gcr.io/my_docker_repo # required for deployments using `ko`
+test/presubmit-tests.sh --integration-tests
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/README.md]: but I need to use `K8S_CLUSTER_OVERRIDE` if I want to use a specific pre-existing cluster right? ([notes section in the docs](https://github.com/knative/test-infra/blob/13055d769cc5e1756e605fcb3bcc1c25376699f1/scripts/README.md#using-the-e2e-testssh-helper-script))

[the remark this answers is not in the document]
Comment (adrcunha) [reply test/README.md]: Yes: https://github.com/knative/test-infra/tree/master/scripts#using-the-e2e-testssh-helper-script

File: test/README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (adrcunha) [reply test/README.md]: Yes, it's kubetest. No, boskos is not used locally, thus you need to set PROJECT_ID.

File: test/cluster-setup.sh [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+    echo ">>> $crd:"
+    kubectl get $crd -o yaml --all-namespaces
+  done
+  echo ">>> Pipeline controller log:"
+  kubectl -n knative-build-pipeline logs $(kubectl -n knative-build-pipeline get pods -l app=build-pipeline-controller -o name)
+  echo ">>> Pipeline webhook log:"
+  kubectl -n knative-build-pipeline logs $(kubectl -n knative-build-pipeline get pods -l app=build-pipeline-webhook -o name)
+}
+
+set +o xtrace
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/cluster-setup.sh]: did the kitten die of delight b/c it was so happy to be able to see lines as they execute? :D

maybe you know a better way to handle this? I'd like to output the commands as I run them, but then it's hard b/c the functions I'm calling also do that, or alternatively don't work well when I do that, so it's hard to handle

File: test/README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/README.md]: ah kk, so i should say kubetest here

File: test/presubmit-tests.sh [hunk 12]
```diff
@@ -43,7 +46,21 @@ function unit_tests() {
 
 function integration_tests() {
   echo "Running integration tests"
-  echo "TODO(#16): add integration tests"
+
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/presubmit-tests.sh]: > I strongly suggest that you move this to a separate script (and even call it e2e-tests.sh).
Source the e2e-tests.sh in vendor. You don't need a separate cluster-setup.sh file, it's just 2 helpers. 1 script is enough.

i'm kind of confused - right now I have `presubmit-tests.sh` and `cluster-setup.sh`, which i think does what you're suggesting `e2e-tests.sh` does, except it doesn't actually call `report_go_test` - is it important that `report_go_test` is called from the other script?

> You're not emitting metrics, so you can omit that part for now, for simplicity.

I think since I've included all the machinery in the tests to be able to emit metrics I might as well keep it

File: test/cluster-setup.sh (hunk 1 above)
Comment (bobcatfish) [reply test/cluster-setup.sh]: How do I work around needing `--run-tests`?

File: test/cluster-setup.sh (hunk 9 above)
[the remark this answers is not in the document]
Comment (adrcunha) [reply test/cluster-setup.sh]: Yes, when running locally `teardown` is called to ensure a clean state. You could use some existing checks in teardown to avoid the situation you described, like `wait_until_object_does_not_exist`.

File: test/presubmit-tests.sh [hunk 13]
```diff
@@ -43,7 +46,21 @@ function unit_tests() {
...
+  # Use knative test-infra scripts to make `fail-test` and `success` available.
+  # which will output helpful information for debugging failures, and ensure test
+  # results are made available.
+  source $(dirname $0)/../vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
+  # Setup the cluster (if not using an existing cluster) and deploy the Pipeline CRD
+  source $(dirname $0)/cluster-setup.sh
+
+  options=""
```
Comment (adrcunha) [inline test/presubmit-tests.sh]: If you update knative/test-infra to HEAD, you replace lines 57-61 with simply

`go_test_e2e ./test || fail_test`

File: test/cluster-setup.sh (hunk 2 above)
Comment (bobcatfish) [reply test/cluster-setup.sh]: whoops, thanks for catching this! i think this should actually be checking `KO_DOCKER_REPO`... i think :thinking:

File: test/cluster-setup.sh (hunk 3 above)
Comment (bobcatfish) [reply test/cluster-setup.sh]: this script doesn't actually run the tests, just sets up the cluster and waits for it to be up, but `presubmit-tests.sh` which is actually running the tests calls `success`

File: test/init_test.go (hunk 4 above)
Comment (bobcatfish) [reply test/init_test.go]: hahaha nice!

(good pick @aaron-prindle :wink: )

File: test/presubmit-tests.sh (hunk 5 above)
Comment (bobcatfish) [reply test/presubmit-tests.sh]: in the above conversation i think we established that you _do_ need `K8S_CLUSTER_OVERRIDE` to use a predefined cluster:

image

File: test/README.md [hunk 14]
```diff
@@ -127,4 +127,29 @@ You can run this locally with:
 
 ```shell
 test/presubmit-tests.sh
-```
\ No newline at end of file
+test/presubmit-tests.sh --build-tests
+test/presubmit-tests.sh --unit-tests
+```
+
+The configuration for these tests lives
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/README.md]: I can reword this, but the idea so that curious folks can understand how Prow is actually setup and triggering this.

File: test/presubmit-tests.sh (hunk 12 above)
[the remark this answers is not in the document]
Comment (adrcunha) [reply test/presubmit-tests.sh]: > is it important that report_go_test is called from the other script?

No. But `e2e-tests.sh` assumes it's being called from the main script, so it can call kubetest and hide the complexity from the main script. Since you're sourcing it from inside a function, there's a good chance of conflicts (e.g., flags) and weird flows.

If your idea is that `cluster-setup.sh` is a helper script to setup an existing cluster for your tests, you don't need (and actually shouldn't) source `e2e-tests.sh`. Just assume the environment is ready and do your stuff.

> You're not emitting metrics, so you can omit that part for now, for simplicity.

Outdated comment, now that the helper function is available. You get metrics for free, without cluttering your script.

File: test/cluster-setup.sh (hunk 1 above)
Comment (adrcunha) [reply test/cluster-setup.sh]: You don't need `--run-tests`, unless you want to run your tests against an already up-and-running cluster. In this case you need the environment vars: https://github.com/knative/test-infra/tree/master/scripts#using-the-e2e-testssh-helper-script (note 2).

File: test/cluster-setup.sh (hunk 2 above)
Comment (adrcunha) [reply test/cluster-setup.sh]: If you're using ko, then yes.

File: test/cluster-setup.sh (hunk 3 above)
Comment (adrcunha) [reply test/cluster-setup.sh]: This is the wrong flow. `presubmit-tests.sh` calls `success` because you sourced the helper. This setup only works because you're not passing any parameters. But since the e2e helper passes the caller script to kubetest, you're probably rerunning the entire presubmit flow (or maybe the setup script, because you double sourced the helper? I don't know). Anyway, this is only working by chance, because that's not how they were meant to be used. Probably that's the major reason why you're seeing weird behavior and resorting to several hacks in your scripts.

File: test/presubmit-tests.sh (hunk 5 above)
Comment (adrcunha) [reply test/presubmit-tests.sh]: There are 3 different contexts here:
* running on Prow (line 17), you don't need to provide anything
* running locally, you can just set PROJECT_ID and the test will create a new cluster for you
* running locally, you can set K8S_* **and** use `--run-tests` **but not with `presubmit-tests.sh`** to run the tests against your cluster

This is only true because you hardcoded `--run-tests` in your script, which is not needed.

File: test/cluster-setup.sh (hunk 1 above)
Comment (bobcatfish) [reply test/cluster-setup.sh]: hm but when using an already created cluster, I need to provide `--run-tests` so that `e2e-tests.sh` [will setup a cluster instead of creating one](https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L302):

image

Comment (bobcatfish) [reply test/cluster-setup.sh]: but using `presubmit-tests.sh` prevents me from being able to pass `--run-tests` since [it isn't a recognized argument](https://github.com/knative/test-infra/blob/master/scripts/presubmit-tests.sh#L83)

File: test/presubmit-tests.sh (hunk 5 above)
Comment (bobcatfish) [reply test/presubmit-tests.sh]: > running locally, you can set K8S_* and use --run-tests but not with presubmit-tests.sh to run the tests against your cluster

hm so I'd have to provide another entrypoint that doesn't source `presubmit-tests.sh` for running locally?

i'm kind of okay with the hack for now, if i can keep the same entrypoint

File: test/cluster-setup.sh (hunk 1 above)
Comment (adrcunha) [reply test/cluster-setup.sh]: You don't provide `--run-tests` to `e2e-tests.sh` (unless it's from command line), it will take care of it itself.

File: test/presubmit-tests.sh (hunk 5 above)
Comment (adrcunha) [reply test/presubmit-tests.sh]: Christie, the root cause of all this confusion is that you're implementing the scripts in a way that the helpers were not intended to be used. This is causing all sort of hacks, confusions and wasted work (like debugging and unnecessary changes in knative/test-infra).

If you just follow the recipe used by all the other repos, things will be easier, you won't need any hacks and you'll have all that you want: presubmit, integration tests on prow and integration tests locally.

**Comment by bobcatfish** [comment]
hm so it seems like some secret mechanism is trying to call our script with `--run-tests`:

```
1003 21:14:58.492] 2018/10/03 21:14:58 process.go:153: Running: /go/src/github.com/knative/build-pipeline/test/presubmit-tests.sh --run-tests
```

**Comment by bobcatfish** [comment]
> knative/serving seems to call e2e-tests.sh with --run-tests:

> Which is weird cuz the knative/serving prow config is using e2e-tests.sh 🤔

@adrcunha is this why you want me to make an `e2e-tests.sh` script with an entrypoint for running the tests, would it be picked up by prow?

(and if so, where is the logic that is doing this?)

**Comment by bobcatfish** [comment]
image

```
W1004 18:06:09.954] 2018/10/04 18:00:49 error processing import paths in "config/201-clusterrolebinding.yaml": the environment variable KO_DOCKER_REPO must be set to a valid docker repository, got a repository name must be specified
W1004 18:06:09.954] 2018/10/04 18:00:49 error processing import paths in "config/300-pipelineparams.yaml": the environment variable KO_DOCKER_REPO must be set to a valid docker repository, got a repository name must be specified
```

:thinking:

**Comment by bobcatfish** [comment]
YUUUUUSSSSS
image

NOOOOOOOOO
image

so close!

File: test/cluster-setup.sh [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+
+# Called by `fail_test` (provided by `e2e-tests.sh`) to dump info on test failure
+function dump_extra_cluster_state() {
+  for crd in pipelines pipelineruns tasks taskruns resources pipelineparams
+  do
+    echo ">>> $crd:"
+    kubectl get $crd -o yaml --all-namespaces
+  done
+  echo ">>> Pipeline controller log:"
+  kubectl -n knative-build-pipeline logs $(kubectl -n knative-build-pipeline get pods -l app=build-pipeline-controller -o name)
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/cluster-setup.sh]: Looks like it's `get_app_pod`, thanks!

File: test/cluster-setup.sh (hunk 11 above)
[the remark this answers is not in the document]
Comment (bobcatfish) [reply test/cluster-setup.sh]: When everything works then it's nice not to have the clutter introduced by xtrace, however it's been experience that things often go wrong, and it's very hard to debug bash without knowing what's actually getting executed.

Even in the context of this PR, things have gone wrong, and it's been hard to understand why because I can't see everything that's happening.

And even now I have really no idea how most of this works, and I can't find what's actually being called (e.g. what's calling boskos? what's the mechanism that's looking for the `e2e-tests.sh` script and calling it with `--run-tests`? where does `DOCKER_REPO_OVERRIDE` get set?)

File: test/cluster-setup.sh (hunk 7 above)
Comment (bobcatfish) [reply test/cluster-setup.sh]: Thanks @pivotal-nader-ziada ! Adding :)

File: test/presubmit-tests.sh (hunk 5 above)
Comment (bobcatfish) [reply test/presubmit-tests.sh]: In https://github.com/knative/build-pipeline/pull/87/commits/60e4470183dc4261ffd7ee328ea32166f7ea4f13 I've made my best attempt to use the helpers in the way they were intended to be used, and it seems to have helped, but there was really only one thing I was doing differently, which was that I didn't have a script called `e2e-tests.sh` which invoked my tests.

I was doing my best to comply with what the other repos were doing, but did not expect that the name of the files I was creating was part of the interface, or that some unseen mechanism (which I still can't track down - where is the boskos logic?) would look `e2e-tests.sh` and call it with `--run-tests`.

The docs you added at https://github.com/knative/test-infra/blob/master/scripts/README.md will go a long way to helping clear this up, but even seeing those docs (when they were in the script itself), I still didn't understand how this was going to be called, and looking at the Prow configs wasn't enough.

It would go a long way to making this easier to be able to easily trace through exactly what code will be executed by Prow (and by the image Prow is calling?).

> This is causing all sort of hacks, confusions and wasted work (like debugging and unnecessary changes in knative/test-infra).

As far as I can tell, the cluster creation scripts still won't work without `BUILD_NUMBER` being defined, and that caused the issue that I mis-diagnosed and tried to fix in test-infra.

File: test/presubmit-tests.sh (hunk 13 above)
Comment (bobcatfish) [reply test/presubmit-tests.sh]: kk will do, thanks

Comment (bobcatfish) [reply test/presubmit-tests.sh]: er wait, but then I'd have to source `e2e-tests.sh` in this file? I think I'm going to leave this for now, I've gotten nervous about what will happen when I source a script :sweat_smile:

File: test/e2e-tests.sh [hunk 16]
```diff
@@ -0,0 +1,92 @@
+#!/bin/bash
```
Comment (tejal29) [inline test/e2e-tests.sh]: If this gets more complex, we could also run this in go and then use exec.Command. https://github.com/grafeas/kritis/blob/master/integration/run_test.go#L146

Sorry, shd have mentioned this before.

Comment (tejal29) [reply test/e2e-tests.sh]: hmm after looking at the comments, looks like this script is prow specific and needs to be there

**Comment by bobcatfish** [comment]
The only remaining problem I can see is that when we look at the build logs, it looks like there is an error:

image

```
I1004 21:05:29.771] Waiting until namespace knative-build-pipeline does not exist........Error from server (NotFound): namespaces "knative-build-pipeline" not found
I1004 21:05:32.067] Waiting until namespace knative-build does not exist.Error from server (NotFound): namespaces "knative-build" not found
```

Submitting a fix to `test-infra` for this in https://github.com/knative/test-infra/pull/175

/hold cancel
/meow space
